[project]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
name = "EMLvp"
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
lxml = ">=5.3.0,<6"
click = ">=8.1.7,<9"
daiquiri = ">=3.0.0,<4"
python = ">=3.13.1,<3.14"
pip = ">=24.3.1,<25"
pixi-pycharm = ">=0.0.8,<0.0.9"

[feature.test.dependencies]
pytest = "*"
pylint = "*"
black = "*"

[feature.test.tasks]
test = "pytest"

[environments]
test = ["test"]
